version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: telegram_forwarder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://postgres:your_password_here@postgres:5432/telegram_forwarder
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PORT=8443
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
